import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import reactRefreshPlugin from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Read rather than detected. `version: 'detect'` sends eslint-plugin-react through a filesystem probe
// that calls an ESLint API removed in 10, and the plugin has no release that does not — 7.37.5 is its
// latest and peers `^9.7`. Taking the version from the manifest keeps the rules that need it working
// and cannot drift from what is installed, which a literal here could.
const reactVersion = JSON.parse(readFileSync(join(import.meta.dirname, 'package.json'), 'utf8')).dependencies.react;

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/node_modules/**',
      '**/.next/**',
      '**/coverage/**',
      'client/dist/**',
      '**.databricks/**',
      // Generated by `appkit generate-types`. Empty in practice now that the
      // assessment SQL lives in config/statements rather than the directory the
      // plugin generates from — see server/collect/sql/queries.ts for why it moved.
      // Linting generated output produces findings nobody can act on, and the
      // shape varies with whether typegen could reach a warehouse.
      'shared/appkit-types/**',
    ],
  },

  // Base JavaScript config
  js.configs.recommended,

  // TypeScript config for all TS files
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // React config for client-side files
  {
    files: ['client/**/*.{ts,tsx}', '**/*.tsx'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      'react-refresh': reactRefreshPlugin,
    },
    settings: {
      react: {
        version: reactVersion,
      },
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      ...reactPlugin.configs['jsx-runtime'].rules,
      ...reactHooksPlugin.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'react/prop-types': 'off', // Using TypeScript for prop validation
      'react/no-array-index-key': 'warn',
    },
  },

  // Node.js specific config for server files
  {
    files: ['server/**/*.ts', '*.config.{js,ts}'],
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
    },
  },

  // Disable type-checking for JS config files and standalone config files
  {
    files: ['**/*.js', '*.config.ts', '**/*.config.ts'],
    ...tseslint.configs.disableTypeChecked,
  },

  // Build-time Node tooling. These are deliberately plain ESM rather than part
  // of a tsconfig project, so the type-aware rules have no program to work from.
  {
    files: ['scripts/**/*.mjs', 'config/**/*.mjs', 'tests/**/*.{ts,tsx}'],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      ...tseslint.configs.disableTypeChecked.languageOptions,
      parserOptions: {
        ...tseslint.configs.disableTypeChecked.languageOptions?.parserOptions,
        projectService: false,
        project: false,
        program: null,
      },
      // Node's own globals, rather than a hand-listed few. The list was already
      // wrong once: adding a script that used URL failed lint for a reason that
      // had nothing to do with the script.
      globals: globals.nodeBuiltin,
    },
  },

  // Prettier config (must be last to override other formatting rules)
  prettier,

  // Custom rules
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  }
);
