// The API's shapes, as the browser receives them.
//
// Re-exported from the shared contract rather than declared again here. The previous
// version of this file was a hand-written copy, on the reasonable argument that the
// server's types use `Date` and JSON does not — and it drifted within a day: the
// footprint changed shape on the server, this file still described the old one, and the
// overview page compiled cleanly while rendering nothing.
//
// The contract takes the date representation as a type parameter, so the difference
// between the two sides is stated in the one place it exists. The server builds
// `ScanPayload<Date>`; the names below are the `string` defaults.

export type {
  GateEligibilityPayload as GateEligibility,
  GateEligibilityReasonPayload as GateEligibilityReason,
  GateEligibilityStatePayload as GateEligibilityState,
} from '../../../shared/api/eligibility';

export type {
  ApiErrorPayload as ApiError,
  AskedBecause,
  AttestableRequirementPayload as AttestableRequirement,
  AttestationPayload as Attestation,
  AttestationState,
  AttestationsPayload as Attestations,
  AcceptedRiskPayload as AcceptedRisk,
  AttestedAnswer,
  AttestedFactPayload as AttestedFact,
  AttemptAnswerPayload as AttemptAnswer,
  AttemptCheckPayload as AttemptCheck,
  AttemptMethodPayload as AttemptMethod,
  AttemptResultPayload as AttemptResult,
  AuditEventPayload as AuditEvent,
  AuditHeadPayload as AuditHead,
  AuditTrailPayload as AuditTrail,
  AuditVerificationPayload as AuditVerification,
  CataloguePayload as CatalogueResponse,
  ControlChangePayload as ControlChange,
  ControlPayload as CatalogueControl,
  ConfidencePayload as Confidence,
  ConfidenceStanding,
  CoveragePayload as Coverage,
  DecisionPayload as Decision,
  DecisionsPayload as Decisions,
  DiagnosticsPayload as Diagnostics,
  Disposition,
  EvidencePayload as Evidence,
  ExecutionMode,
  ExportFilePayload as ExportFile,
  ExportRecordPayload as ExportRecord,
  ExportVariantPayload as ExportVariantFiles,
  FinalisationPayload as Finalisation,
  FindingPayload as Finding,
  FootprintPayload as ScanFootprint,
  FoundationReadinessPayload as FoundationReadiness,
  GuidanceAdvicePayload as GuidanceAdvice,
  GuidanceCheckKind,
  GuidanceCheckPayload as GuidanceCheck,
  GuidanceExamplesPayload as GuidanceExamples,
  GuidancePayload as Guidance,
  GuidanceResponse,
  Horizon,
  // `Improvement` rather than `Action` for the record: `AuditAction` is already a thing this app
  // calls an action, and two unqualified `Action`s in one import list is how they get confused.
  ActionsForControlPayload as ActionsForControl,
  ActionsRaisedPayload as ActionsRaised,
  ActionEffortPayload as ActionEffort,
  ActionPriorityPayload as ActionPriority,
  ActionStatePayload as ActionState,
  ActionTransitionPayload as ActionTransition,
  AdviceProvenancePayload as AdviceProvenance,
  AdviceReadingPayload as AdviceReading,
  AdviceReferencePayload as AdviceReference,
  AdviceStandingPayload as AdviceStanding,
  AdvisorPayload as Advisor,
  AgreementPayload as Agreement,
  ImprovementActionPayload as ImprovementAction,
  ImprovementPlanDetailPayload as ImprovementPlanDetail,
  ImprovementPlanPayload as ImprovementPlan,
  ImprovementsPayload as Improvements,
  LatenessPayload as Lateness,
  PlanProgressPayload as PlanProgress,
  LimitationPayload as Limitation,
  LocatedItemPayload as LocatedItem,
  LocatedPayload as Located,
  MeasurementPayload as Measurement,
  NoteCountsPayload as NoteCounts,
  NotePayload as Note,
  NoteSubjectKindPayload as NoteSubjectKind,
  NoteSubjectPayload as NoteSubject,
  NoteThreadPayload as NoteThread,
  NoteThreadsPayload as NoteThreads,
  OccurrencePayload as Occurrence,
  Outcome,
  OutcomeCountsPayload as OutcomeCounts,
  MethodologyPayload as Methodology,
  MethodologyRequirementPayload as MethodologyRequirement,
  CatalogueSpanPayload as CatalogueSpan,
  CatalogueRevisionPayload as CatalogueRevision,
  PillarPayload as CataloguePillar,
  PillarPlanPayload as PillarPlan,
  PillarScorePayload as PillarScore,
  PillarTargetPayload as PillarTarget,
  TargetReadingPayload as TargetReading,
  TargetStandingPayload as TargetStanding,
  PlanPayload as Plan,
  PlannedSignalPayload as PlannedSignal,
  PrinciplePayload as CataloguePrinciple,
  ProvenancePayload as Provenance,
  PublicMethodologyIdentityPayload as PublicMethodologyIdentity,
  PublicMethodologyStatePayload as PublicMethodologyState,
  // Not `Reading`: `Provenance` above is already the evidence one, and a second unqualified name for
  // a different kind of provenance in the same import list is how the two get confused at a call site.
  ReadingPayload as HealthReading,
  PlanExportsPayload as PlanExports,
  ReadinessDimensionPayload as ReadinessDimension,
  RemediationPayload as Remediation,
  RemedyKind,
  RemedyPayload as Remedy,
  RequirementPayload as Requirement,
  RevocationPayload as Revocation,
  RiskStandingPayload as RiskStanding,
  RisksPayload as Risks,
  RunChangesPayload as RunChanges,
  RunExportsPayload as RunExports,
  ScanHistoryPayload as ScanHistory,
  ScanPayload as Scan,
  ScanState,
  ScanStatusPayload as ScanStatus,
  ScanSummaryPayload as ScanSummary,
  SchedulePayload as Schedule,
  ScheduleRunPayload as ScheduleRun,
  ScheduleStatePayload as ScheduleState,
  ScheduleTriggerPayload as ScheduleTrigger,
  ServerlessJobPayload as ServerlessJob,
  ServerlessReadinessPayload as ServerlessReadiness,
  ServerlessReasonPayload as ServerlessReason,
  ServerlessRuleKind,
  ServerlessVerdict,
  ServingDeclarationPayload as ServingDeclaration,
  CostAssumptionPayload as CostAssumption,
  CostRangePayload as CostRange,
  ScorePayload as Score,
  ScoreRangePayload as ScoreRange,
  ExposurePayload as Exposure,
  ExclusionPayload as Exclusion,
  LapsePayload as Lapse,
  ApplicabilityLeverPayload as ApplicabilityLever,
  Severity,
  SignalPayload as SignalSummary,
  SpendPayload as Spend,
  Standing,
  Unmeasured,
  StampPayload as ScanStamp,
  SurfaceActivityPayload as SurfaceFootprint,
  SurfaceCostPayload as SurfaceCost,
  SurfacePayload as CollectionSurface,
  UnansweredPayload as Unanswered,
  ValidationAttemptPayload as ValidationAttempt,
  ValidationsPayload as Validations,
  ValueMeasuredPayload as ValueMeasured,
  ValueMoneyPayload as ValueMoney,
  ValueReportPayload as ValueReport,
  DefinitionPayload as AssessmentDefinition,
  DefinitionVersionPayload as DefinitionVersion,
  DefinitionsPayload as Definitions,
  DefinitionScopePayload as DefinitionScope,
  DefinitionMeasurementPayload as DefinitionMeasurement,
  DefinitionAttributionPayload as DefinitionAttribution,
  DraftTargetPayload as DraftTarget,
  SelectableWorkspacePayload as SelectableWorkspace,
  SelectableWorkspacesPayload as SelectableWorkspaces,
  SetupDraftPayload as SetupDraft,
  SetupDraftsPayload as SetupDrafts,
  ScopePreviewPayload as ScopePreview,
  PreflightPayload as Preflight,
  PreflightSourcePayload as PreflightSource,
  PreflightBlockedPayload as PreflightBlocked,
  PreflightScopePayload as PreflightScope,
  EvidenceScriptPayload as EvidenceScript,
  EvidenceImportPayload as EvidenceImport,
  EvidenceImportsPayload as EvidenceImports,
  EvidenceImportVerdictPayload as EvidenceImportVerdict,
  EvidenceNotePayload as EvidenceNote,
  EligibilityPayload as Eligibility,
  LegalHoldPayload as LegalHold,
  RetentionClassPayload as RetentionClass,
  RetentionPayload as Retention,
  SweepPayload as Sweep,
  ResetPlanPayload as ResetPlan,
  ResetPayload as Reset,
  AdvisoryPayload as Advisory,
  AdvisoryLinePayload as AdvisoryLine,
  AdvisoryHistoryPayload as AdvisoryHistory,
  WorkloadPayload as Workload,
  WorkloadShapePayload as WorkloadShape,
  WorkloadFindingPayload as WorkloadFinding,
  WorkloadTrendPayload as WorkloadTrend,
  WorkloadEvidencePayload as WorkloadEvidence,
  WorkloadCoveragePayload as WorkloadCoverage,
  SizingPayload as Sizing,
  SizingFindingPayload as SizingFinding,
  WarehouseSizingPayload as WarehouseSizing,
  WarehouseStatePayload as WarehouseState,
  JobsPayload as Jobs,
  JobFindingPayload as JobFinding,
  JobHealthPayload as JobHealth,
  JobComputePayload as JobCompute,
  ComputeReachPayload as ComputeReach,
  JobStatePayload as JobState,
  WritePayload as Writes,
  WriteFindingPayload as WriteFinding,
  WriteShapePayload as WriteShape,
  WriteStatePayload as WriteState,
  AssessmentReviewPayload as AssessmentReview,
  AssessmentResultPayload as AssessmentResult,
  OpenReviewsPayload as OpenReviews,
  CurrentResultPayload as CurrentResult,
  FinalResultHistoryPayload as FinalResultHistory,
  PillarReviewPayload as PillarReview,
  ReviewAnswerPayload as ReviewAnswer,
} from '../../../shared/api/contract';

export type {
  MonthContentPayload as MonthContent,
  MonthDeltaPayload as MonthDelta,
  MonthDocumentPayload as MonthDocument,
  MonthExceptionPayload as MonthException,
  MonthFactPayload as MonthFact,
  MonthIdPayload as MonthId,
  MonthMovementPayload as MonthMovement,
  MonthPreviewPayload as MonthPreview,
  MonthStandingPayload as MonthStanding,
  MonthSummaryPayload as MonthSummary,
  MonthTrendPointPayload as MonthTrendPoint,
  MonthsPayload as Months,
  PublishedMonthPayload as PublishedMonth,
  PublishedMonthResultPayload as PublishedMonthResult,
  PublishingZonePayload as PublishingZone,
} from '../../../shared/api/month';
