// Reading the guidance that makes a question answerable.
//
// "Standardize DevOps processes (CI/CD): is this practice in place?" is not a question anybody can
// answer honestly, because it does not say which standard is being held up. The catalogue offers the
// title and the question and nothing else, so an answer to it today is a guess with a timestamp on
// it — and a guess that becomes a score is worse than an unanswered requirement, which at least
// reports as unanswered.
//
// So each answerable requirement gets authored guidance: what the practice means, why it matters as
// the risk of not doing it, what good looks like as the rubric an answer is measured against, three
// worked examples so a reader can place themselves honestly, where to look to check, the ways it is
// commonly got wrong, and when "partially" is the true answer.
//
// Structured fields rather than a markdown blob, for three reasons. Every question reads the same way
// regardless of who wrote it. The schema can require the fields that matter, so nothing ships
// half-written. And there is no parser and no sanitisation burden, because React escapes text and the
// panel renders no raw HTML — a markdown field would put an XSS decision inside a content file.
//
// The files live in `config/guidance/` rather than beside the controls because `config/controls/` is
// generated by scripts/seed-catalogue.mjs, which warns against editing entries by hand. Authored
// prose in a generated file is prose that a re-seed eventually eats.

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadAll } from 'js-yaml';
import { shippedConfigDirectory } from '../shipped-config.js';

/** Whether anybody has written this entry yet. A draft is a scaffold and the app says so. */
export type GuidanceStatus = 'draft' | 'authored';

export type CheckKind = 'ui' | 'sql' | 'cli' | 'api' | 'by-hand';

export interface GuidanceCheck {
  readonly how: CheckKind;
  readonly where: string;
  readonly expect?: string;
  /** What the check cannot establish, where a clean result would otherwise read as a good one. */
  readonly caveat?: string;
}

export interface GuidanceExamples {
  readonly strong: string;
  readonly partial: string;
  readonly weak: string;
}

/**
 * What to do about the requirement, as against how to answer a question about it.
 *
 * The fields above make a question answerable, and stop at the answer. These six say where to get
 * to, how, at what cost, what to keep and when the decision reopens — which is what a finding needs
 * and a question does not. Both halves come from one entry so there is one corpus rather than two
 * that disagree.
 *
 * Present or absent as a block, never in part. A recommendation rendered without its trade-offs is a
 * recommendation with the cost hidden, and the reader cannot tell that the author wrote one and not
 * the other.
 */
export interface GuidanceAdvice {
  /** The safe default for a customer with no established policy. */
  readonly startFrom: string;
  /** What changes it, each saying what it changes it to. */
  readonly dependsOn: readonly string[];
  /** Observed state to baseline to target, in order. */
  readonly path: readonly string[];
  /** What following that path costs. */
  readonly costs: readonly string[];
  /** The artefact that proves this at the next review. */
  readonly retain: string;
  /** The event or cadence that reopens the decision. */
  readonly revisit: string;
}

export interface Guidance {
  readonly controlId: string;
  readonly pillarId: string;
  readonly status: GuidanceStatus;
  readonly lastReviewed?: string;
  readonly ownerRole?: string;
  readonly means?: string;
  readonly matters?: string;
  readonly good: readonly string[];
  readonly examples?: GuidanceExamples;
  readonly verify: readonly GuidanceCheck[];
  readonly pitfalls: readonly string[];
  readonly partialWhen?: string;
  readonly notApplicableWhen?: string;
  readonly references: readonly string[];
  readonly advice?: GuidanceAdvice;
}

export interface GuidanceLibrary {
  /** Every entry, keyed by control id, draft ones included. */
  readonly entries: ReadonlyMap<string, Guidance>;
  /** How many are written, which is the number the completeness ratchet holds. */
  readonly authored: number;
  /** How many of those also carry advice, which is the second ratchet and rises separately. */
  readonly advised: number;
}

export function guidanceDirectory(moduleUrl = import.meta.url): string {
  return shippedConfigDirectory('guidance', moduleUrl);
}

/**
 * Every guidance file, read and keyed by control id.
 *
 * Nothing here validates against the schema: `npm run check:guidance` does that, and doing it again
 * at boot would mean a content mistake takes the app down instead of showing up in CI. What this does
 * instead is read defensively — a missing field is `undefined` and an entry that says nothing reads as
 * a draft — so the worst a malformed file can do is leave a question without its guidance, which is
 * the state every question is in until row 10 of the plan authors it anyway.
 */
export function loadGuidance(directory: string = guidanceDirectory()): GuidanceLibrary {
  const files = readdirSync(directory)
    .filter((name) => name.endsWith('.yaml'))
    .sort();

  const entries = new Map<string, Guidance>();
  for (const name of files) {
    // `loadAll`, not `load`: an empty file is a file with no documents in it, and `load` reads that as
    // an error rather than as nothing. A malformed file still throws, which is the half of the old
    // behaviour worth keeping — the defence above is against a file that says nothing, not one that lies.
    const [raw] = loadAll(readFileSync(join(directory, name), 'utf8')) as (RawFile | null)[];
    if (raw?.entries == null) continue;

    for (const [controlId, entry] of Object.entries(raw.entries)) {
      if (entry == null) continue;
      entries.set(controlId, toGuidance(controlId, raw.pillar ?? name.replace(/\.yaml$/, ''), entry));
    }
  }

  const written = [...entries.values()].filter((one) => one.status === 'authored');
  return { entries, authored: written.length, advised: written.filter((one) => one.advice != null).length };
}

/**
 * The guidance a question should show, or nothing.
 *
 * A draft returns nothing on purpose. The panel's alternative to showing a draft is saying "no
 * guidance has been written for this question yet", and that sentence is more useful than a heading
 * with an empty body under it: one tells the reader to ask a colleague, the other reads as a bug.
 */
export function authoredGuidance(library: GuidanceLibrary, controlId: string): Guidance | undefined {
  const found = library.entries.get(controlId);
  return found?.status === 'authored' ? found : undefined;
}

interface RawFile {
  pillar?: string;
  entries?: Record<string, RawEntry | null>;
}

interface RawEntry {
  status?: string;
  last_reviewed?: string;
  owner_role?: string;
  means?: string;
  matters?: string;
  good?: string[];
  examples?: { strong?: string; partial?: string; weak?: string };
  verify?: { how?: string; where?: string; expect?: string; caveat?: string }[];
  pitfalls?: string[];
  partial_when?: string;
  not_applicable_when?: string;
  references?: string[];
  advice?: {
    start_from?: string;
    depends_on?: string[];
    path?: string[];
    costs?: string[];
    retain?: string;
    revisit?: string;
  };
}

const KINDS: readonly CheckKind[] = ['ui', 'sql', 'cli', 'api', 'by-hand'];

function toGuidance(controlId: string, pillarId: string, raw: RawEntry): Guidance {
  const examples =
    raw.examples?.strong != null && raw.examples.partial != null && raw.examples.weak != null
      ? { strong: raw.examples.strong, partial: raw.examples.partial, weak: raw.examples.weak }
      : undefined;

  return {
    controlId,
    pillarId,
    status: raw.status === 'authored' ? 'authored' : 'draft',
    good: raw.good ?? [],
    verify: (raw.verify ?? []).flatMap((check) => (check.where == null ? [] : [toCheck(check)])),
    pitfalls: raw.pitfalls ?? [],
    references: raw.references ?? [],
    ...present('lastReviewed', raw.last_reviewed),
    ...present('ownerRole', raw.owner_role),
    ...present('means', raw.means),
    ...present('matters', raw.matters),
    ...present('examples', examples),
    ...present('partialWhen', raw.partial_when),
    ...present('notApplicableWhen', raw.not_applicable_when),
    ...present('advice', toAdvice(raw.advice)),
  };
}

/**
 * Advice, or nothing — never some of it.
 *
 * `check:guidance` refuses a partial block, so a file in the tree has all six or none. This is what
 * happens when one is edited out by hand between checks: the block is dropped rather than rendered
 * with a gap, because the panel's headings would otherwise announce a trade-off nobody wrote.
 *
 * The types say `string` and `string[]`, and this checks anyway, because they describe YAML — the
 * declared shape of a file the loader was pointed at, not a shape anything enforced. Two states get
 * past a null check and neither is theoretical: `start_from:` with nothing after it parses as an
 * empty string, which renders as a heading over nothing; and `depends_on: one factor` parses as a
 * scalar, which has a `length` and would reach `.map` in the panel as a string and take the page
 * down with it.
 */
function toAdvice(raw: RawEntry['advice']): GuidanceAdvice | undefined {
  if (raw == null) return undefined;
  const { start_from: startFrom, depends_on: dependsOn, path, costs, retain, revisit } = raw;
  if (!written(startFrom) || !written(retain) || !written(revisit)) return undefined;
  if (!listed(dependsOn) || !listed(path) || !listed(costs)) return undefined;
  return { startFrom, dependsOn, path, costs, retain, revisit };
}

const written = (value: unknown): value is string => typeof value === 'string' && value.trim() !== '';
const listed = (value: unknown): value is string[] => Array.isArray(value) && value.length > 0 && value.every(written);

function toCheck(raw: { how?: string; where?: string; expect?: string; caveat?: string }): GuidanceCheck {
  const how = KINDS.find((kind) => kind === raw.how) ?? 'by-hand';
  return { how, where: raw.where ?? '', ...present('expect', raw.expect), ...present('caveat', raw.caveat) };
}

/** Absent stays absent, rather than becoming an explicit undefined on every entry. */
function present<K extends string, V>(key: K, value: V | undefined): Partial<Record<K, V>> {
  return value === undefined ? {} : ({ [key]: value } as Record<K, V>);
}
