#!/usr/bin/env node

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Marked } from 'marked';
import { load as loadYaml } from 'js-yaml';

const APP = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = resolve(APP, '..', 'docs');
const WRITE = process.argv.includes('--write');
const PAGES = [
  ['index.md', 'index.html'],
  ['install.md', 'install/index.html'],
  ['configuration.md', 'configuration/index.html'],
  ['user-guide.md', 'user-guide/index.html'],
  ['pages.md', 'pages/index.html'],
  ['operations.md', 'operations/index.html'],
  ['troubleshooting.md', 'troubleshooting/index.html'],
  ['contributing.md', 'contributing/index.html'],
  ['deployment-lifecycle.md', 'deployment-lifecycle/index.html'],
  ['scheduled-scans.md', 'scheduled-scans/index.html'],
  ['404-source.md', '404.html'],
];

const config = loadYaml(readFileSync(join(DOCS, '_config.yml'), 'utf8'));
const layout = readFileSync(join(DOCS, '_layouts/default.html'), 'utf8');
const base = config.baseurl ?? '';
const failures = [];

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function frontMatter(document, source) {
  const match = document.match(/^---\n([\s\S]*?)\n---\n?/);
  if (match == null) throw new Error(`${source} has no YAML front matter.`);
  return { attributes: loadYaml(match[1]) ?? {}, body: document.slice(match[0].length) };
}

function relativeUrls(value) {
  return value.replace(/\{\{\s*'([^']+)'\s*\|\s*relative_url\s*\}\}/g, (_whole, path) => `${base}${path}`);
}

function imageClasses(value) {
  return value.replace(
    /^!\[([^\]]*)\]\(([^)]+)\)\{:[ \t]*\.([A-Za-z0-9_-]+)[ \t]*\}[ \t]*$/gm,
    (_whole, alt, src, className) =>
      `<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}" class="${escapeHtml(className)}">`
  );
}

function slug(value) {
  return String(value)
    .replace(/<[^>]+>/g, '')
    .replace(/[`*_~]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function renderMarkdown(value) {
  const seen = new Map();
  const marked = new Marked({
    gfm: true,
    renderer: {
      heading({ tokens, depth, text }) {
        const content = this.parser.parseInline(tokens);
        const stem = slug(text) || 'section';
        const count = seen.get(stem) ?? 0;
        seen.set(stem, count + 1);
        const id = count === 0 ? stem : `${stem}-${count + 1}`;
        return `<h${depth} id="${id}">${content}</h${depth}>\n`;
      },
      link({ href, title, tokens }) {
        let target = href;
        const local = href.match(/^([^/#]+)\.md(#[^\s]*)?$/);
        if (local != null) target = `${base}/${local[1]}/${local[2] ?? ''}`;
        const titleAttribute = title == null ? '' : ` title="${escapeHtml(title)}"`;
        return `<a href="${escapeHtml(target)}"${titleAttribute}>${this.parser.parseInline(tokens)}</a>`;
      },
    },
  });
  return marked.parse(imageClasses(relativeUrls(value)));
}

function renderLayout(attributes, content, source) {
  const pageTitle = attributes.title == null ? '' : `${escapeHtml(attributes.title)} · `;
  const description = escapeHtml(attributes.description ?? config.description ?? '');
  const eyebrow = attributes.eyebrow == null ? '' : `<p class="eyebrow">${escapeHtml(attributes.eyebrow)}</p>`;
  const rendered = relativeUrls(layout)
    .replace('{% if page.title %}{{ page.title }} · {% endif %}', pageTitle)
    .replace('{{ site.title }}', escapeHtml(config.title))
    .replace('{{ page.description | default: site.description | escape }}', description)
    .replace('{% if page.eyebrow %}<p class="eyebrow">{{ page.eyebrow }}</p>{% endif %}', eyebrow)
    .replace('{{ content }}', content);
  if (rendered.includes('{{') || rendered.includes('{%')) {
    throw new Error(`${source} left an unresolved Liquid expression in its generated page.`);
  }
  return rendered
    .replace(
      '<html lang="en">',
      `<!-- Generated by app/scripts/build-pages.mjs from ${source}. -->\n<html lang="en">`
    )
    .replace(/[ \t]+$/gm, '')
    .replace(/\n+$/, '\n');
}

for (const [sourceName, targetName] of PAGES) {
  const source = readFileSync(join(DOCS, sourceName), 'utf8');
  const { attributes, body } = frontMatter(source, sourceName);
  const expected = renderLayout(attributes, renderMarkdown(body), sourceName);
  const target = join(DOCS, targetName);
  if (WRITE) {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, expected);
  } else if (!existsSync(target) || readFileSync(target, 'utf8') !== expected) {
    failures.push(targetName);
  }
}

if (!existsSync(join(DOCS, '.nojekyll'))) failures.push('.nojekyll');

if (failures.length > 0) {
  console.error(`The branch-published Pages site is stale: ${failures.join(', ')}. Run npm run docs:build.`);
  process.exit(1);
}

console.log(`${PAGES.length} pre-rendered Pages documents match their Markdown sources.`);
